# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "vmd" "nvme" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d6891251-6f5b-4e6e-a0ea-5966aa99bf74";
    fsType = "btrfs";
    options = ["subvol=root compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d6891251-6f5b-4e6e-a0ea-5966aa99bf74";
    fsType = "btrfs";
    options = ["subvol=nix noatime compress=zstd"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/d6891251-6f5b-4e6e-a0ea-5966aa99bf74";
    fsType = "btrfs";
    options = ["subvol=home compress=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0957-5126";
    fsType = "vfat";
  };

  swapDevices = [];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
