# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  astronaut-sddm-theme = {
    pname = "astronaut-sddm-theme";
    version = "ef7ff4199e0e78c37995938ad4ced402d34edf79";
    src = fetchFromGitHub ({
      owner = "Keyitdev";
      repo = "sddm-astronaut-theme";
      rev = "ef7ff4199e0e78c37995938ad4ced402d34edf79";
      fetchSubmodules = false;
      sha256 = "sha256-I39W9U4j/MbyYp4BlB4sWuQ5GVf/z4bm4ohrSfIWcXI=";
    });
  };
  awesome = {
    pname = "awesome";
    version = "f3cf88593c15a233092972c997528297e546f325";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "f3cf88593c15a233092972c997528297e546f325";
      fetchSubmodules = false;
      sha256 = "sha256-U/+aLp4fHUTULk+EqP2vtzeVD5FDcUPH53owQ835G7k=";
    });
  };
  catppuccin-spicetify = {
    pname = "catppuccin-spicetify";
    version = "8aaacc4b762fb507b3cf7d4d1b757eb849fcbb52";
    src = fetchFromGitHub ({
      owner = "catppuccin";
      repo = "spicetify";
      rev = "8aaacc4b762fb507b3cf7d4d1b757eb849fcbb52";
      fetchSubmodules = false;
      sha256 = "sha256-yfRbYM065wRJqaZB+SsOZi4+e2+ZOD0iKyhNVBJcrqA=";
    });
  };
  coc-tailwindcss3 = {
    pname = "coc-tailwindcss3";
    version = "263eeeaa14e7efe7056fdca92e0c60801425b912";
    src = fetchFromGitHub ({
      owner = "yaegassy";
      repo = "coc-tailwindcss3";
      rev = "263eeeaa14e7efe7056fdca92e0c60801425b912";
      fetchSubmodules = false;
      sha256 = "sha256-71x7h91ruLgckVIJFWCGp7LellIS25nHfGd7uzDYEyk=";
    });
  };
  copilot-vim = {
    pname = "copilot-vim";
    version = "1bfbaf5b027ee4d3d3dbc828c8bfaef2c45d132d";
    src = fetchFromGitHub ({
      owner = "github";
      repo = "copilot.vim";
      rev = "1bfbaf5b027ee4d3d3dbc828c8bfaef2c45d132d";
      fetchSubmodules = false;
      sha256 = "sha256-hm/8q08aIVWc5thh31OVpVoksVrqKD+rSHbUTxzzHaU=";
    });
  };
  nvim-cokeline = {
    pname = "nvim-cokeline";
    version = "8d5022789014a605d5a2ec02ed5133eb85874aff";
    src = fetchFromGitHub ({
      owner = "noib3";
      repo = "nvim-cokeline";
      rev = "8d5022789014a605d5a2ec02ed5133eb85874aff";
      fetchSubmodules = false;
      sha256 = "sha256-mG0cJelaZLNth5mc9QNBuhlWzo+1pfeOAz+REtgUY8o=";
    });
  };
  nwg-panel = {
    pname = "nwg-panel";
    version = "v0.7.6";
    src = fetchFromGitHub ({
      owner = "nwg-piotr";
      repo = "nwg-panel";
      rev = "v0.7.6";
      fetchSubmodules = false;
      sha256 = "sha256-OtwpYqSdh9zPVnz6By/TMi93vDky6OO74syulUp97FQ=";
    });
  };
  picom = {
    pname = "picom";
    version = "db16da3907b2ba540be5a53d0f0e28e2d3b5b705";
    src = fetchFromGitHub ({
      owner = "yaocccc";
      repo = "picom";
      rev = "db16da3907b2ba540be5a53d0f0e28e2d3b5b705";
      fetchSubmodules = false;
      sha256 = "sha256-q0VI5/5jPQR+Rd7cxdLF+bMNeO+JoxTmBwAS0WqW7gQ=";
    });
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "v2.12.0";
    src = fetchFromGitHub ({
      owner = "khanhas";
      repo = "spicetify-cli";
      rev = "v2.12.0";
      fetchSubmodules = false;
      sha256 = "sha256-QJfR6DtsblNCTssT2tvli6FNFzK9+lqyRLSTQXOH4Ok=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "0f7a687e76c525e4013a7f82ccb15e11cc30475a";
    src = fetchFromGitHub ({
      owner = "morpheusthewhite";
      repo = "spicetify-themes";
      rev = "0f7a687e76c525e4013a7f82ccb15e11cc30475a";
      fetchSubmodules = false;
      sha256 = "sha256-OI0CiZE9GKaXVa5I8kCXlrfjX8izynKi5sJxPQK0Zd8=";
    });
  };
  vim-astro = {
    pname = "vim-astro";
    version = "34732be5e9a5c28c2409f4490edf92d46d8b55a9";
    src = fetchFromGitHub ({
      owner = "wuelnerdotexe";
      repo = "vim-astro";
      rev = "34732be5e9a5c28c2409f4490edf92d46d8b55a9";
      fetchSubmodules = false;
      sha256 = "sha256-HyQ4i/T1uQmGurBqCpo8+ESVSVPsTrLQBxLe2OEYjcY=";
    });
  };
  zscroll = {
    pname = "zscroll";
    version = "788be9650b647f61f8f899054ad1213eee42e8a4";
    src = fetchFromGitHub ({
      owner = "noctuid";
      repo = "zscroll";
      rev = "788be9650b647f61f8f899054ad1213eee42e8a4";
      fetchSubmodules = false;
      sha256 = "sha256-gEluWzCbztO4N1wdFab+2xH7l9w5HqZVzp2LrdjHSRM=";
    });
  };
}
