# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  astronaut-sddm-theme = {
    pname = "astronaut-sddm-theme";
    version = "ef7ff4199e0e78c37995938ad4ced402d34edf79";
    src = fetchFromGitHub ({
      owner = "Keyitdev";
      repo = "sddm-astronaut-theme";
      rev = "ef7ff4199e0e78c37995938ad4ced402d34edf79";
      fetchSubmodules = false;
      sha256 = "sha256-I39W9U4j/MbyYp4BlB4sWuQ5GVf/z4bm4ohrSfIWcXI=";
    });
  };
  catppuccin-spicetify = {
    pname = "catppuccin-spicetify";
    version = "8aaacc4b762fb507b3cf7d4d1b757eb849fcbb52";
    src = fetchFromGitHub ({
      owner = "catppuccin";
      repo = "spicetify";
      rev = "8aaacc4b762fb507b3cf7d4d1b757eb849fcbb52";
      fetchSubmodules = false;
      sha256 = "sha256-yfRbYM065wRJqaZB+SsOZi4+e2+ZOD0iKyhNVBJcrqA=";
    });
  };
  coc-tailwindcss3 = {
    pname = "coc-tailwindcss3";
    version = "33f981b70bed862033863773f921d7c27f6f1bc9";
    src = fetchFromGitHub ({
      owner = "yaegassy";
      repo = "coc-tailwindcss3";
      rev = "33f981b70bed862033863773f921d7c27f6f1bc9";
      fetchSubmodules = false;
      sha256 = "sha256-cFyA/WDlLEUKbpuZVL04UvAAJ18wqjScaRN9BubzvwM=";
    });
  };
  copilot-vim = {
    pname = "copilot-vim";
    version = "1bfbaf5b027ee4d3d3dbc828c8bfaef2c45d132d";
    src = fetchFromGitHub ({
      owner = "github";
      repo = "copilot.vim";
      rev = "1bfbaf5b027ee4d3d3dbc828c8bfaef2c45d132d";
      fetchSubmodules = false;
      sha256 = "sha256-hm/8q08aIVWc5thh31OVpVoksVrqKD+rSHbUTxzzHaU=";
    });
  };
  fleet = {
    pname = "fleet";
    version = "8dce51cab7a13caf1431a07368978bfc191b301c";
    src = fetchFromGitHub ({
      owner = "dimensionhq";
      repo = "fleet";
      rev = "8dce51cab7a13caf1431a07368978bfc191b301c";
      fetchSubmodules = false;
      sha256 = "sha256-EZWY0KjJ68XvumyterziprbIe1wTU4NJbMuWW+gAt4c=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./fleet-8dce51cab7a13caf1431a07368978bfc191b301c/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  nvim-cokeline = {
    pname = "nvim-cokeline";
    version = "501f93ec84af0d505d95d3827cad470b9c5e86dc";
    src = fetchFromGitHub ({
      owner = "noib3";
      repo = "nvim-cokeline";
      rev = "501f93ec84af0d505d95d3827cad470b9c5e86dc";
      fetchSubmodules = false;
      sha256 = "sha256-BQP4jOm55YeDfabsSdfEiRk2O7t7KARklSbyfBK5Zu0=";
    });
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "v2.13.0";
    src = fetchFromGitHub ({
      owner = "khanhas";
      repo = "spicetify-cli";
      rev = "v2.13.0";
      fetchSubmodules = false;
      sha256 = "sha256-XsYZoJDSaAp+oMTy5YWM9aM+TCNkqF5WXBhU/axcEVk=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "0f7a687e76c525e4013a7f82ccb15e11cc30475a";
    src = fetchFromGitHub ({
      owner = "morpheusthewhite";
      repo = "spicetify-themes";
      rev = "0f7a687e76c525e4013a7f82ccb15e11cc30475a";
      fetchSubmodules = false;
      sha256 = "sha256-OI0CiZE9GKaXVa5I8kCXlrfjX8izynKi5sJxPQK0Zd8=";
    });
  };
  zscroll = {
    pname = "zscroll";
    version = "788be9650b647f61f8f899054ad1213eee42e8a4";
    src = fetchFromGitHub ({
      owner = "noctuid";
      repo = "zscroll";
      rev = "788be9650b647f61f8f899054ad1213eee42e8a4";
      fetchSubmodules = false;
      sha256 = "sha256-gEluWzCbztO4N1wdFab+2xH7l9w5HqZVzp2LrdjHSRM=";
    });
  };
}
