# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchFromGitHub,
}: {
  hlchunk-nvim = {
    pname = "hlchunk-nvim";
    version = "a17b86f7c9640410c168f2421bd3753124d40603";
    src = fetchFromGitHub {
      owner = "shellRaining";
      repo = "hlchunk.nvim";
      rev = "a17b86f7c9640410c168f2421bd3753124d40603";
      fetchSubmodules = false;
      sha256 = "sha256-7OCA/6xyoRKybfMDQ3G4fWu+lxarpbZPC6+dJYQaBuY=";
    };
    date = "2023-11-26";
  };
  hoverhints-nvim = {
    pname = "hoverhints-nvim";
    version = "86fad985b91fe454469108924c1cdb378cbae1ce";
    src = fetchFromGitHub {
      owner = "soulis-1256";
      repo = "hoverhints.nvim";
      rev = "86fad985b91fe454469108924c1cdb378cbae1ce";
      fetchSubmodules = false;
      sha256 = "sha256-QQ+ISmwY6NnvzsnY2GZVxXh/2V6LYaXIjD7evScq4HQ=";
    };
    date = "2023-11-23";
  };
}
